TESTS = t/001_basic.sql t/002_models.sql t/003_chat.sql
REGRESS = $(patsubst t/%.sql,%,$(TESTS))
REGRESS_OPTS = --inputdir=t

ifdef USE_PGXS
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
else
subdir = contrib/pg_llm
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
endif 