name: C++ CI with clang-format, Build, and glog on macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job for clang-format checking
  format-check:
    runs-on: macos-latest  # Specify macOS as the runner

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up clang-format tool
      - name: Set up clang-format
        run: brew install clang-format  # Use Homebrew to install clang-format

      # Run clang-format to check code style
      - name: Run clang-format check
        run: |
          # Get the list of modified source files (cpp, h, cc, hpp)
          git diff --exit-code --name-only | grep -E "\.(cpp|h|cc|hpp)$" | xargs clang-format -style=file -i
          # Check if there are any uncommitted changes
          git diff --exit-code

  # Job for building the project and dependencies (including glog)
  build:
    runs-on: macos-latest  # Specify macOS as the runner
    needs: format-check

    steps:
      # Checkout the code from the repository again
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies required for building the project
      - name: Install dependencies
        run: |
          brew update
          brew install cmake pkg-config openssl curl jsoncpp postgresql

      - name: Clean previous thirdparty builds
        run: |
          rm -rf thirdparty/glog
          rm -rf thirdparty/build
          rm -rf thirdparty/install
